-- 账本是成员与消费的归属根节点；删除行为由后续外键定义。
CREATE TABLE IF NOT EXISTS ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ledgers PRIMARY KEY (id),
    CONSTRAINT ck_ledgers_name CHECK (
        name = TRIM(name)
        AND CHAR_LENGTH(name) > 0
    )
);
-- 成员必须属于账本；成员 ID 同时提供稳定创建顺序。
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ledger_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_members PRIMARY KEY (id),
    CONSTRAINT fk_members_ledger FOREIGN KEY (ledger_id) REFERENCES ledgers (id) ON DELETE CASCADE,
    CONSTRAINT uk_members_ledger_name UNIQUE (ledger_id, name),
    CONSTRAINT uk_members_ledger_id UNIQUE (ledger_id, id),
    CONSTRAINT ck_members_name CHECK (
        name = TRIM(name)
        AND CHAR_LENGTH(name) > 0
    )
);
-- 消费金额按分保存；付款人必须属于消费所在账本。
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ledger_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    amount_cents BIGINT NOT NULL,
    expense_date DATE NOT NULL,
    payer_member_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_expenses PRIMARY KEY (id),
    CONSTRAINT fk_expenses_ledger FOREIGN KEY (ledger_id) REFERENCES ledgers (id) ON DELETE CASCADE,
    CONSTRAINT uk_expenses_ledger_id UNIQUE (ledger_id, id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (ledger_id, payer_member_id) REFERENCES members (ledger_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_expenses_title CHECK (
        title = TRIM(title)
        AND CHAR_LENGTH(title) > 0
    ),
    CONSTRAINT ck_expenses_amount CHECK (amount_cents > 0)
);
-- 关系表只记录参与事实，不保存可实时推导的个人分摊金额。
CREATE TABLE IF NOT EXISTS expense_participants (
    ledger_id BIGINT NOT NULL,
    expense_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    CONSTRAINT pk_expense_participants PRIMARY KEY (ledger_id, expense_id, member_id),
    CONSTRAINT fk_expense_participants_expense FOREIGN KEY (ledger_id, expense_id) REFERENCES expenses (ledger_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_participants_member FOREIGN KEY (ledger_id, member_id) REFERENCES members (ledger_id, id) ON DELETE RESTRICT
);
-- 支持消费排序、付款人引用检查和参与人引用检查。
CREATE INDEX IF NOT EXISTS idx_expenses_ledger_date_id ON expenses (ledger_id, expense_date, id);
CREATE INDEX IF NOT EXISTS idx_expenses_ledger_payer ON expenses (ledger_id, payer_member_id);
CREATE INDEX IF NOT EXISTS idx_expense_participants_ledger_member ON expense_participants (ledger_id, member_id);